name: validate

on:
  push:
    branches:
      - 'master'
      - 'releases/v*'
  pull_request:
    branches:
      - 'master'
      - 'releases/v*'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@6fbf6d4271a67721a55f4d3616e60f1dfea39648
      -
        name: Validate
        uses: docker/bake-action@v1
        with:
          targets: validate
